#原镜像
FROM golang:1.17 as builder
#新建文件夹
RUN mkdir /admin
#复制代码
COPY . /admin
#设置工作目录
WORKDIR /admin/sk-admin
#设置代理
ENV GOPROXY https://goproxy.cn,direct
#go构建可执行文件
RUN go build .

FROM centos:latest as runner

#指定工作目录
WORKDIR /go/admin

COPY --from=builder /admin/sk-admin  .
#最终运行docker的命令
ENTRYPOINT  ["./sk-app"]
#docker网络配置，容器通讯。