#原镜像
FROM golang:1.17 as builder
#新建文件夹
RUN mkdir /core
#复制代码
COPY . /core
#设置工作目录
WORKDIR /core/sk-core
#设置代理
ENV GOPROXY https://goproxy.cn,direct
#go构建可执行文件
RUN go build .

FROM centos:latest as runner

#指定工作目录
WORKDIR /go/core

COPY --from=builder /core/sk-core  .
#最终运行docker的命令
ENTRYPOINT  ["./sk-app"]
#docker网络配置，容器通讯。